language: php

env:
    global:
        - SEND_COVERAGE=false

matrix:
  include:
    - php: 5.5
      env:
          - LIBXL_PHP_VERSION=php5
    - php: 5.6
      env:
        - SEND_COVERAGE=true
        - LIBXL_PHP_VERSION=php5
    - php: 7
      env:
        - LIBXL_PHP_VERSION=php7

before_script:
  - mkdir -p test/logs
  - mkdir -p tests/tmp/cache 
  - mkdir -p build/logs
  - travis_retry composer self-update
  - travis_retry composer --prefer-source --dev install
  - test/travis/install_phpexcel_extension.sh $LIBXL_PHP_VERSION
  - echo "extension = excel.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: 
  - phpunit -v 

after_script:
  - if [[ $SEND_COVERAGE == true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ $SEND_COVERAGE == true ]]; then php ocular.phar code-coverage:upload --format=php-clover test/build/logs/clover.xml; fi
